### ISSUE TITLE
I got an error on WSL Ubuntu 

### ISSUE THREAD

**Issue by zonshi** [roof12/kickstart.nvim#1]
## Describe the bug

Error detected while processing /home/username/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/username/.config/nvim/init.lua:162: attempt to index field 'keymap' (a nil value)
stack traceback:
        /home/username/.config/nvim/init.lua:162: in main chunk
Press ENTER or type command to continue

## Desktop

- OS: Linux version 5.15.146.1-microsoft-standard-WSL2 (root@65c757a075e2) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Jan 11 04:09:03 UTC 2024  Ubuntu Ubuntu 22.04.4 LTS
- Terminal: Bash on Windows Terminal

## Neovim Version

NVIM v0.6.1
```
```

**Comment by roof12** [comment]
@zonshi this repo was cloned for personal use, from https://github.com/nvim-lua/kickstart.nvim. I switched to LazyVim so this is not maintained.

I'd recommend starting with the repo above. It looks to still be in active development.
